# Generated by Django 3.0 on 2020-06-04 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='numberPassport',
        ),
        migrations.RemoveField(
            model_name='vagon',
            name='ves_in',
        ),
        migrations.RemoveField(
            model_name='vagon',
            name='ves_out',
        ),
        migrations.AddField(
            model_name='auto',
            name='numberPasport',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='номер passport'),
        ),
        migrations.AddField(
            model_name='auto',
            name='numberPassportList',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='номерsopor list'),
        ),
        migrations.AddField(
            model_name='auto',
            name='typeMaterial',
            field=models.IntegerField(db_index=True, null=True, verbose_name='тип мфтериала'),
        ),
        migrations.AddField(
            model_name='auto',
            name='typeOperation',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='тип операции'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='courseDate',
            field=models.DateField(blank=True, null=True, verbose_name='дата курса '),
        ),
        migrations.AddField(
            model_name='vagon',
            name='description',
            field=models.TextField(db_index=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='discont',
            field=models.FloatField(db_index=True, null=True, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='executer',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='исполнитель'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='nakladnayaDate',
            field=models.DateField(blank=True, null=True, verbose_name='дата накладной '),
        ),
        migrations.AddField(
            model_name='vagon',
            name='nds',
            field=models.FloatField(db_index=True, null=True, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='numberAttorney',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='номер доверенности'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='numberNakladnaia',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='номер в накладной'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='numberPasport',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='номер passport'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='numberPassportList',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='номерsopor list'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='numberSeats',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='количество мест'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='operatrion',
            field=models.IntegerField(null=True, verbose_name='operartion'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='organization',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='организация'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='osnovanie',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='основание'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='parentcontractid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.CatalogContract'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='parentresponseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.CatalogResponsiblePerson'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='parentuserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vagon',
            name='pogruzka',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='место погрузки'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='price',
            field=models.FloatField(db_index=True, null=True, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='price_ed',
            field=models.CharField(max_length=100, null=True, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='price_ed_iz',
            field=models.FloatField(db_index=True, null=True, verbose_name='цена ed'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='price_no_nds',
            field=models.FloatField(db_index=True, null=True, verbose_name='цена  без ндс'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='prinyal',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='кто принял'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='putlist',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='номер путевого листа'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='razreshil',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='кто разрешил'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='seria',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='серия накладной'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='store',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='склад'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='type',
            field=models.IntegerField(db_index=True, null=True, verbose_name='тип накладной'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='typeMaterial',
            field=models.IntegerField(db_index=True, null=True, verbose_name='тип мфтериала'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='typeOperation',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='тип операции'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='ves_ed',
            field=models.CharField(max_length=100, null=True, verbose_name='еденицы измерения'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='ves_nakladnaya',
            field=models.FloatField(db_index=True, null=True, verbose_name='вес по накладной'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='weghtIn',
            field=models.FloatField(db_index=True, null=True, verbose_name='вес пустой'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='weghtOut',
            field=models.FloatField(db_index=True, null=True, verbose_name='вес полной'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='netto',
            field=models.FloatField(db_index=True, null=True, verbose_name='вес clear'),
        ),
    ]
