# Generated by Django 3.0 on 2020-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagon',
            name='actNumber',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='act'),
        ),
    ]
