# Generated by Django 3.0 on 2020-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0002_auto_20200604_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogcontract',
            old_name='date',
            new_name='datecontract',
        ),
        migrations.RenameField(
            model_name='catalogcontract',
            old_name='parentMaterialId',
            new_name='parentmaterialid',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='characteristicTMC',
            new_name='characteristictmc',
        ),
        migrations.AddField(
            model_name='auto',
            name='path1',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='path1'),
        ),
        migrations.AddField(
            model_name='auto',
            name='path2',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='path2'),
        ),
        migrations.AddField(
            model_name='auto',
            name='path3',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='path3'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='path1',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='path1'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='path2',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='path2'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='path3',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='path3'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='type',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='тип накладной'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='typeMaterial',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='тип мфтериала'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='type',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='тип накладной'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='typeMaterial',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='тип мфтериала'),
        ),
    ]
